onCull = true
MaxEntityEntities = 1024
qualityModes = "ULTRA"
RenderWeather = "NORMAL"
FastItemRender = false
RenderDisplayItem = false
blackListedEntities = []
whiteListedEntities = []
isAlwaysShowItemCount = true
startTime = 152.626
chatFix = false
onGui = true
GuiRXTX = false
GuiFPS = true
GuiCPU = true
GuiGPU = true
GuiRAM = true
GuiEntityCount = true
GuiPlayerPos = true
GuiServer = true
GuiCameraTarget = false
Mood = false
Particle = true
BlockBreakParticleMode = "LOW"
MaxParticleDistance = 512
WhiteListedParticle = []
BlackListedParticle = []
FPSMonitor = true
GuiEasyRamMode = true
GuiDisplayRamUsage = false
GuiX = 0
GuiY = 0
EntityRender = true
UseAui = false
DeBug = false
TextBackground = false
TextureAnimatedSprites = true
SoundDevicesMonitor = true
SetParticleMaxAge = true
ParticleMaxAge = 1
GuiViewMode = "NULL"
EntityCullFov = 120
MinDistance = 5
EntityDistance = 512
TickPerformance = false
